// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Verifier } from "./tables/Verifier.sol";
import { ClaimedGift } from "./tables/ClaimedGift.sol";
